# https://hub.docker.com/_/storm
version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  nimbus:
    image: storm:2.6.0
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  ui:
    image: storm:2.6.0
    container_name: ui
    command: storm ui
    depends_on:
      - zookeeper
      - nimbus
    links:
      - zookeeper
      - nimbus
    restart: always
    ports:
      - 8000:8080

  supervisor:
    image: storm:2.6.0
    container_name: supervisor
    command: storm supervisor
    volumes:
      - ./:/demo
      - ./conf:/apache-storm-2.6.0/conf
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always